# Generated by Django 3.2.15 on 2022-09-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='priority',
            new_name='prio',
        ),
    ]
