# Generated by Django 3.2.15 on 2022-08-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='desg',
            field=models.TextField(default='anything'),
        ),
    ]
